spring:
  data:
    mongodb:
      port: 0
      database: hw13mongoDB

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:h2:mem:maindb
    driverClassName: org.h2.Driver
    username: sa
    password: 1


  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  logging:
    level:
      sql: debug

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
